apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
  namespace: {{ .AddonInstallNamespace }}
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:

    exporters:
      otlp:
        endpoint: otlp-grpc-otel-gateway-route-observability.apps.iba413ipi01.maistra.upshift.redhat.com
        tls:
          insecure: false
          cert_file: /certs/tls.crt
          key_file: /certs/tls.key
          ca_file: /certs/ca.crt

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]
  volumes:
    - name: certs
      secret: 
        secretName: mtls-spoke-hub-otel
  volumeMounts:
    - name: certs
      mountPath: /certs
