apiVersion: v1
kind: Secret
metadata:
  name: mtls-spoke-hub-otel
  namespace: {{ .AddonInstallNamespace }}
data:
  'tls.crt': {{ .mTLS.cert }}
  'tls.key': {{ .mTLS.key }}
  'ca.crt': {{ .mTLS.ca }}
