apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: otel-addon
spec:
  addOnMeta:
    displayName: OpenTelemetry Addon
    description: "AddOn to deploy OpenTelemetry Collectors in OCM/ACM"
