kind: Deployment
apiVersion: apps/v1
metadata:
  name: otel-addon-controller
  labels:
    app: otel-addon-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-addon-controller
  template:
    metadata:
      labels:
        app: otel-addon-controller
    spec:
      serviceAccountName: otel-addon-sa
      containers:
      - name: otel-addon-controller
        image: quay.io/open-cluster-management/addon-examples
        imagePullPolicy: Always
        args:
          - "/busybox"