namespace: open-cluster-management

resources:
- resources/cluster_role.yaml
- resources/cluster_role_binding.yaml
- resources/service_account.yaml
- resources/otel_clustermanagementaddon.yaml
- resources/otel_addon_controller.yaml

images:
- name: quay.io/open-cluster-management/addon-examples
  newName: ttl.sh/otel-addon
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
