apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-ca
  namespace: observability
spec:
  isCA: true
  commonName: otel-ca
  subject:
    organizations:
      - Demo.
    organizationalUnits:
      - AddOns
  secretName: otel-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
