apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: otel-ca
  secretName: otel-ca-secret
  privateKey:
    algorithm: RSA
    size: 4096
    encoding: PKCS8
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
