apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-gateway
  namespace: observability
spec:
  secretName: otel-gateway
  commonName: otel-gateway
  subject:
    organizationalUnits:
      - otel-ocm-addon
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  dnsNames:
    - otel-gateway.observability.svc
  usages:
    - server auth
    - key encipherment
    - digital signature
  issuerRef:
    name: otel-ca-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster1
  namespace: cluster1
spec:
  secretName: cluster1
  commonName: cluster1
  subject:
    organizationalUnits:
      - otel-ocm-addon
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  dnsNames:
    - otel-gateway.observability.svc
  usages:
    - client auth
    - key encipherment
    - digital signature
  issuerRef:
    name: otel-ca-issuer
    kind: ClusterIssuer
