apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  mode: "deployment"
  # https://github.com/open-telemetry/opentelemetry-operator/issues/2449
  # ingress:
  #   type: ingress
  #   annotations:
  #     nginx.ingress.kubernetes.io/rewrite-target: /$2
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      debug:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug]
