apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otlp-receiver
spec:
  mode: "deployment"
  ingress:
    type: route
    route:
      termination: "edge"
  config: |
    receivers:
      otlp:
        protocols:
          http:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
